version: '3.8'

services:
  web:
    build: .  # Build the web app using the Dockerfile
    container_name: web_app
    ports:
      - "5000:5000"  # Map host port 5000 to container port 5000
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mydb
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:13  # Use the official PostgreSQL image
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist database data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data: